### ISSUE TITLE
how to run the code?

### ISSUE THREAD

**Issue by prabhakar267** [stonewell/lib7zip#1]
Not able to run the code on my local machine.
Can you please help with  a step-by-step procedure to run the code on my machine. I am using Ubuntu 14.04 LTS

**Comment by zackse** [comment]
Are you asking how to compile this library, how to run the test suite, or how to write code that uses the library?

**Comment by prabhakar267** [comment]
@zackse replying after 2 years 😆 
I hardly remember why I was using this library 
Closing the issue
