### ISSUE TITLE
lib7zip is thread-safe or not?

### ISSUE THREAD

**Issue by DK1998U** [stonewell/lib7zip#10]
i had tried multi thread with lib7zip.But unfortunatly got a error core dump

**Comment by stonewell** [comment]
we never tested on multiple thread, so I am assuming it is not

**Comment by DK1998U** [comment]
thanks&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jingnan Si"<notifications@github.com&gt;; 
发送时间: 2020年9月29日(星期二) 中午12:23
收件人: "stonewell/lib7zip"<lib7zip@noreply.github.com&gt;; 
抄送: "1"<312453651@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [stonewell/lib7zip] lib7zip is thread-safe or not? (#10)





 
we never tested on multiple thread, so I am assuming it is not

**Comment by stonewell** [comment]
close
