### ISSUE TITLE
How do I run the code?

### ISSUE THREAD

**Issue by markb-trustifi** [stonewell/lib7zip#11]
I successfully created the `bin/7z.so` library in the `p7zip` project by running `make 7z`.
After that I built `lib7zip` sources by `cmake -DBUILD_SHARED_LIB=OFF -DP7ZIP_SOURCE_DIR=/xxx/p7zip_16.02` 
What do I do now? 
I want to build and run `Test7Zip.cpp` as a portable executable.

**Comment by stonewell** [comment]
after build lib7zip, you will get the Test7Zip binary in test folder, set LD_LIBRARY_PATH to the 7z.so directory, then run Test7zip binary

**Comment by markb-trustifi** [comment]
The Test7Zip binary means 'feature_tests.bin' in Mac?
I run it with existing file `Test7Zip.7z` in the same dir and nothing happens.

**Comment by stonewell** [comment]
after you finish the cmake, run make in the folder, you will get Test7Zip in test/ folder as a executable binary, the name is exactly "Test7Zip"

**Comment by markb-trustifi** [comment]
@stonewell Thank you for your help! I have now another question. I see, the Test7Zip.cpp extracts 1 file from the archive. Is there a way to extract multiple files?
