### ISSUE TITLE
Compilation Fails on Linux

### ISSUE THREAD

**Issue by courageon** [stonewell/lib7zip#2]
Getting this error on linux:

```
7ZipArchive.cpp:8:34: fatal error: CPP/myWindows/StdAfx.h: No such file or directory
 #include "CPP/myWindows/StdAfx.h"
                                  ^
compilation terminated.
```

...can't figure out what flags to set to tell make that I'm not on WIN32

**Comment by zackse** [comment]
> I guess this is not really appropriate for a question about Linux, but I felt I had to write it somewhere.

Please file a separate bug for problems compiling on Windows. This bug is about Linux compilation, which uses different code (p7zip vs 7zip) and a different compiler.

**Comment by sfinktah** [comment]
I don't care enough.  I have supplied information that is useful, you can choose whether to incorporate it into your library / knowledgebase / whatever, or not.

I don't have a problem, or a bug report.  I fixed my problem.

Enjoy :)

**Comment by zackse** [comment]
Hi @sfinktah, I'm not the maintainer of this library, but I'm not sure this information is all that useful attached to a bug about linux compilation. Please consider contributing to the project by opening another issue, adding a wiki page, or even a pull request. Thanks!

**Comment by sfinktah** [comment]
Thanks, but I contribute to enough projects already.
