### ISSUE TITLE
failed to extract the rar file

### ISSUE THREAD

**Issue by OUC-MYM** [stonewell/lib7zip#4]
I failed to extract the rar file using Test7Zip/Test7ZipRar5.cpp on Linux. It can create new files but not write bytes. I am using p7zip_16.02.

**Comment by stonewell** [comment]
p7zip by default didn't not include the rar.so, could you confirm you can extract rar files using 7za command under linux?

**Comment by OUC-MYM** [comment]
I merged 7z.so and rar.so.
It is ok.
