### ISSUE TITLE
error on windows

### ISSUE THREAD

**Issue by Fav** [stonewell/lib7zip#6]
C:\Program Files (x86)\Windows Kits\8.1\Include\um\winioctl.h(39): error C2374: “GUID_DEVINTERFACE_DISK”: 重定义；多次初始化
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winioctl.h(39): note: 参见“GUID_DEVINTERFACE_DISK”的声明
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\winioctl.h(40): error C2374: “GUID_DEVINTERFACE_CDROM”: 重定义；多次初始化
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winioctl.h(40): note: 参见“GUID_DEVINTERFACE_CDROM”的声明
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\winioctl.h(41): error C2374: “GUID_DEVINTERFACE_PARTITION”: 重定义；多次初始化
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winioctl.h(41): note: 参见“GUID_DEVINTERFACE_PARTITION”的声明
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\winioctl.h(42): error C2374: “GUID_DEVINTERFACE_TAPE”: 重定义；多次初始化
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winioctl.h(42): note: 参见“GUID_DEVINTERFACE_TAPE”的声明
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\winioctl.h(43): error C2374: “GUID_DEVINTERFACE_WRITEONCEDISK”: 重定义；多次初始化
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winioctl.h(43): note: 参见“GUID_DEVINTERFACE_WRITEONCEDISK”的声明
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\winioctl.h(44): error C2374: “GUID_DEVINTERFACE_VOLUME”: 重定义；多次初始化
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\um\winioctl.h(44): note: 参见“GUID_DEVINTERFACE_VOLUME”的声明

when i remove line 6~8   
//#ifndef INITGUID
//#define INITGUID
//#endif

lib7zip is ok , but Test7Zip can not run ,error is 
1>7zip.lib(7ZipOpenArchive.obj) : error LNK2001: 无法解析的外部符号 IID_IInStream
1>7zip.lib(7ZipInStreamWrapper.obj) : error LNK2001: 无法解析的外部符号 IID_IInStream
1>7zip.lib(7ZipOpenArchive.obj) : error LNK2001: 无法解析的外部符号 IID_IArchiveOpenVolumeCallback
1>7zip.lib(7ZipOpenArchive.obj) : error LNK2001: 无法解析的外部符号 IID_IInArchiveGetStream
1>7zip.lib(7ZipOpenArchive.obj) : error LNK2001: 无法解析的外部符号 IID_IArchiveOpenSetSubArchiveName
1>7zip.lib(7ZipOpenArchive.obj) : error LNK2001: 无法解析的外部符号 IID_IInArchive

**Comment by Fav** [comment]
I user  vs2015

**Comment by Jesson029** [comment]
github上面用中文   鬼才会回复你   老外不看的
你改成英文的   才可能回复的
